### PR TITLE
for Firefox

### PR DESCRIPTION
**Pull request by utaani**
camera node for Firefox

### CODE REVIEW

**Comment by chughts** [comment]
Thanks for your contribution. Your proposed change is currently being reviewed, but we anticipate that we will be accepting the change soon.

**Comment by gibfahn** [comment]
Sorry for the slow reply!

So as I understand it `navigator.mozGetUserMedia` is useful for old versions of Firefox but is now deprecated. Is this still necessary for compatibility with old browsers?

I also see that `navigator.getUserMedia` is deprecated in favour of `navigator.mediaDevices.getUserMedia`, presumably we should be supporting this as well?

cc/ @yrezgui @ChrisParsonsDev

**Comment by utaani** [comment]
my firefox is 49.0.2, no mozGetUserMedia fire alert. screen shot
and if mozGetUserMedia is deprecated in future, it will no problem.

**Review by gibfahn — APPROVED** [review]
LGTM

**Pull request merged**
