### PR TITLE
fix image type in help to png.

### PR DESCRIPTION
**Pull request by utaani**
canvas.toBlob default format is png. I tested on Firefox 49.0.2 and Chrome 54.0.2840.99 m on Windows.

### CODE REVIEW

**Comment by chughts** [comment]
So is the image type different depending on machine it is being run on?

**Comment by utaani** [comment]
It use canvas.toBlob to make a capture from canvas in camera/camera.html line 87, and canvas.toBlob default format is PNG. cf. https://www.w3.org/TR/html5/scripting-1.html#the-canvas-element

BTW, I tested on MacOS with Chrome 54.0.2840.98 and Firefox 49.0.2, they make PNG. I cannot test on Safari because Safari does not support camera inject node now.

**Comment by utaani** [comment]
hmm, My test win and mac point that default is PNG, and w3.org TR say PNG too. Are you test another platform and any other results? What is reason JPG in help?

**Comment by utaani** [comment]
If you want to the image format to JPEG, it is possible by specified by the second argument of toBlob. cf. https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob#Parameters

**Comment by chughts** [comment]
Reason for jpg in help is most likely a documentation error. What we have seems to work for the visual recognition service, so I would opt to change the help, rather than the code.

**Pull request merged**
